### ISSUE TITLE
 Vision Pose Class

### ISSUE THREAD

**Issue by josephhadad05** [Creekside-Robotics/2023-Robot-Code#2]
### Completing this Issue
Create a new Subsystem class, `VisionObjectAPI`. This class will have to a method to access the object data currently on NetworkTables.

You will need to have a method that returns the name and position of the closest object, with an object type parameter.

Look at Nate's issue ([#1](https://github.com/Creekside-Robotics/2023-Vision-Processing-Code/issues/1)) to see how values were entered into NetworkTables.

### Helpful Docs
* [WPILIB NetworkTables](https://docs.wpilib.org/en/stable/docs/software/networktables/index.html) - WPILIB docs for NetworkTables.
* [Subsystems WPILIB](https://docs.wpilib.org/en/stable/docs/software/commandbased/subsystems.html) - WPILIB docs for Subsystems in FRC.
* [Geometry Classes WPILIB](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/geometry/pose.html) - WPILIB docs on its geometry classes, `Pose2d` will be helpful for this issue.

As always, if you need help, just ping me on discord. Thank you!

**Comment by BenI570** [comment]
closed by #3
